import { DownloadOutlined, EyeOutlined, FileExcelOutlined, FilePdfOutlined, MoreOutlined, SearchOutlined, } from "@ant-design/icons";
import { Button, DatePicker, Dropdown, Input, Select, Table, Tag, Tooltip, } from "antd";
import type { ColumnsType } from "antd/es/table";
import type { MenuProps } from "antd";
import type { Report } from "../admin.interface";

const { RangePicker } = DatePicker;

const reports: Report[] = [
    {
        key: "1",
        reportName: "Monthly Job Report",
        type: "Jobs",
        generatedBy: "Admin",
        generatedDate: "10 Sep 2026",
        records: 1248,
        status: "Generated",
    },
    {
        key: "2",
        reportName: "Candidate Registration Report",
        type: "Candidates",
        generatedBy: "Admin",
        generatedDate: "09 Sep 2026",
        records: 3542,
        status: "Generated",
    },
    {
        key: "3",
        reportName: "Application Summary",
        type: "Applications",
        generatedBy: "Admin",
        generatedDate: "08 Sep 2026",
        records: 5820,
        status: "Generated",
    },
    {
        key: "4",
        reportName: "Recruiter Activity Report",
        type: "Recruiters",
        generatedBy: "Admin",
        generatedDate: "07 Sep 2026",
        records: 486,
        status: "Generated",
    },
    {
        key: "5",
        reportName: "Company Registration Report",
        type: "Companies",
        generatedBy: "Admin",
        generatedDate: "06 Sep 2026",
        records: 325,
        status: "Processing",
    },
    {
        key: "6",
        reportName: "Job Application Status Report",
        type: "Applications",
        generatedBy: "Admin",
        generatedDate: "05 Sep 2026",
        records: 4380,
        status: "Generated",
    },
    {
        key: "7",
        reportName: "Platform User Report",
        type: "Users",
        generatedBy: "Admin",
        generatedDate: "04 Sep 2026",
        records: 8120,
        status: "Generated",
    },
    {
        key: "8",
        reportName: "Job Performance Report",
        type: "Jobs",
        generatedBy: "Admin",
        generatedDate: "03 Sep 2026",
        records: 986,
        status: "Failed",
    },
];

const Reports = () => {
    /* =========================
       Action Menu
    ========================= */

    const actionMenu = (record: Report): MenuProps => ({
        items: [
            {
                key: "view",
                icon: <EyeOutlined />,
                label: "View Report",
            },
            {
                key: "download",
                icon: <DownloadOutlined />,
                label: "Download",
            },
        ],
        onClick: ({ key }) => {
            console.log(`${key} report:`, record);
        },
    });

    /* =========================
       Export Menu
    ========================= */

    const exportMenu: MenuProps = {
        items: [
            {
                key: "csv",
                icon: <FileExcelOutlined />,
                label: "Export CSV",
            },
            {
                key: "pdf",
                icon: <FilePdfOutlined />,
                label: "Export PDF",
            },
        ],
        onClick: ({ key }) => {
            console.log(`Export ${key}`);
        },
    };

    /* =========================
       Table Columns
    ========================= */

    const columns: ColumnsType<Report> = [
        {
            title: "Report",
            dataIndex: "reportName",
            key: "reportName",
            width: 300,
            render: (reportName: string) => (
                <Tooltip title={reportName}>
                    <span className="block max-w-[260px] truncate font-medium text-[#0F172A]">
                        {reportName}
                    </span>
                </Tooltip>
            ),
        },

        {
            title: "Type",
            dataIndex: "type",
            key: "type",
            width: 160,
            render: (type: string) => (
                <Tag className="!m-0 !rounded-md !border-[#D1D6DC] !bg-[#F8FAFC] !px-2 !text-[#475467]">
                    {type}
                </Tag>
            ),
        },

        {
            title: "Generated By",
            dataIndex: "generatedBy",
            key: "generatedBy",
            width: 160,
            render: (generatedBy: string) => (
                <span className="text-sm text-[#475467]">
                    {generatedBy}
                </span>
            ),
        },

        {
            title: "Generated Date",
            dataIndex: "generatedDate",
            key: "generatedDate",
            width: 170,
            render: (date: string) => (
                <span className="text-sm text-[#475467]">
                    {date}
                </span>
            ),
        },

        {
            title: "Records",
            dataIndex: "records",
            key: "records",
            width: 120,
            render: (records: number) => (
                <span className="font-medium text-[#0F172A]">
                    {records.toLocaleString()}
                </span>
            ),
        },

        {
            title: "Status",
            dataIndex: "status",
            key: "status",
            width: 140,
            render: (status: Report["status"]) => {
                const color =
                    status === "Generated"
                        ? "success"
                        : status === "Processing"
                            ? "processing"
                            : "error";

                return (
                    <Tag color={color} className="!rounded-full !px-3">
                        {status}
                    </Tag>
                );
            },
        },

        {
            title: "Actions",
            key: "actions",
            width: 80,
            fixed: "right",
            render: (_, record) => (
                <Dropdown
                    menu={actionMenu(record)}
                    trigger={["click"]}
                    placement="bottomRight"
                >
                    <Button
                        type="text"
                        icon={<MoreOutlined />}
                        className="!flex !items-center !justify-center !rounded-lg"
                    />
                </Dropdown>
            ),
        },
    ];

    return (
        <div className="flex h-full flex-col gap-4">
            {/* =========================
          Toolbar
      ========================= */}

            <div className="flex flex-wrap items-center justify-between gap-3">
                {/* Filters */}

                <div className="flex flex-wrap items-center gap-3">
                    <Input
                        prefix={
                            <SearchOutlined className="text-[#98A2B3]" />
                        }
                        placeholder="Search reports"
                        allowClear
                        className="!w-[230px] !rounded-xl !border !border-solid !border-[#D1D6DC] !shadow-none"
                    />

                    <Select
                        placeholder="Report Type"
                        allowClear
                        className="!w-[160px]"
                        options={[
                            {
                                label: "Jobs",
                                value: "Jobs",
                            },
                            {
                                label: "Candidates",
                                value: "Candidates",
                            },
                            {
                                label: "Applications",
                                value: "Applications",
                            },
                            {
                                label: "Recruiters",
                                value: "Recruiters",
                            },
                            {
                                label: "Companies",
                                value: "Companies",
                            },
                            {
                                label: "Users",
                                value: "Users",
                            },
                        ]}
                    />

                    <Select
                        placeholder="Status"
                        allowClear
                        className="!w-[140px]"
                        options={[
                            {
                                label: "Generated",
                                value: "Generated",
                            },
                            {
                                label: "Processing",
                                value: "Processing",
                            },
                            {
                                label: "Failed",
                                value: "Failed",
                            },
                        ]}
                    />

                    <RangePicker
                        className="!w-[250px] !rounded-xl !border !border-solid !border-[#D1D6DC] !shadow-none"
                    />
                </div>

                {/* Right Action */}

                <Dropdown
                    menu={exportMenu}
                    trigger={["click"]}
                >
                    <Button
                        icon={<DownloadOutlined />}
                        className="!rounded-full !border !border-solid !border-[#D1D6DC] !bg-white !px-4 !py-2 !text-[#0F172A] !shadow-none"
                    >
                        Export
                    </Button>
                </Dropdown>
            </div>

            {/* =========================
          Table
      ========================= */}

            <div className="min-h-0 flex-1 rounded-2xl bg-white p-4 shadow-[0px_4px_32px_0px_#98A2B31F]">
                <Table
                    columns={columns}
                    dataSource={reports}
                    rowKey="key"
                    scroll={{
                        y: "calc(100vh - 319px)",
                    }}
                    pagination={{
                        pageSize: 10,
                        position: ["bottomRight"],
                        showSizeChanger: false,
                    }}
                    className="reports-table"
                />
            </div>
        </div>
    );
};

export default Reports;